[package]
name = "rpgmasd-wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "WASM bindings for rpgm-asset-decrypter-lib."
repository = "https://github.com/RPG-Maker-Translation-Tools/rpgm-asset-decrypter-lib"
documentation = "https://github.com/RPG-Maker-Translation-Tools/rpgm-asset-decrypter-lib/tree/master/crates/rpgmasd-wasm"
license-file = "LICENSE.md"
keywords = ["rpgmaker", "wasm", "decrypt", "encrypt", "assets"]
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
rpgm-asset-decrypter-lib = { path = "../.." }
wasm-bindgen = "=0.2.127"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory"]
